yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech',)
]

yatube/posts/urls.py
from django.urls import path
from posts import views

app_name = 'posts'

urlpatterns = [
    path(
        '',
        views.index,
        name='index'
    ),
    path(
        'group/<slug:slug>/',
        views.group_posts,
        name='group_list'
    ),
    path(
        'profile/<str:username>/',
        views.profile,
        name='profile'
    ),
    path(
        'posts/<int:post_id>/',
        views.post_detail,
        name='post_detail'
    ),
    path(
        'create/',
        views.post_create,
        name='post_create'
    ),
    path(
        'posts/<int:post_id>/edit/',
        views.post_edit,
        name='post_edit'
    ),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path(
        'follow/',
        views.follow_index,
        name='follow_index'
    ),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler403 = 'core.views.csrf_failure'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Выберите группу'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:settings.FIRST_FIFTEEN_CHARS]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField(
        'Текст',
        help_text='Текст нового комментария'
    )
    created = models.DateTimeField(
        auto_now_add=True
    )

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
    )

    def __str__(self):
        return f'{self.user} follows {self.author}'

yatube/posts/forms.py
from django import forms

from posts.models import Comment, Group, Post


class PostForm(forms.ModelForm):
    group = forms.ModelChoiceField(queryset=Group.objects,
                                   empty_label='Группа не выбрана',
                                   required=False,
                                   label='Группа')

    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {
            'text': 'Текст',
        }
        help_texts = {
            'text': 'Текст нового комментария',
        }

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page
from posts.forms import CommentForm, PostForm
from posts.models import Follow, Group, Post, User


@cache_page(20)
def index(request):
    template = 'posts/index.html'
    post_list = Post.objects.select_related('group')
    paginator = Paginator(post_list, settings.ARTICLES_SELECTION)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    paginator = Paginator(post_list, settings.ARTICLES_SELECTION)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    template = 'posts/profile.html'
    user = request.user
    author = get_object_or_404(User, username=username)
    following = (
        user.is_authenticated
        and Follow.objects.filter(user=user, author=author)
    )
    post_list = author.posts.all().order_by('author')
    paginator = Paginator(post_list, settings.ARTICLES_SELECTION)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    post_number = post_list.count()
    context = {
        'page_obj': page_obj,
        'post_number': post_number,
        'author': author,
        'following': following,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, id=post_id)
    post_list = Post.objects.select_related(
        'group'
    ).filter(
        author_id=post.author
    )
    post_number = post_list.count()
    form = CommentForm(request.POST or None)
    comments = post.comments.all()
    context = {
        'post': post,
        'post_list': post_list,
        'post_number': post_number,
        'form': form,
        'comments': comments
    }
    return render(request, template, context)


@login_required
def post_create(request):
    template = 'posts/create_post.html'
    form = PostForm(request.POST or None)
    context = {
        'form': form,
    }
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect(f'/profile/{post.author.username}/')
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    template = 'posts/create_post.html'
    post = get_object_or_404(Post, id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    context = {
        'form': form,
        'post_id': post_id,
        'post': post,
        'is_edit': True,
    }
    if request.user == post.author and form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect(f'/posts/{post.id}', id=post_id)
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    """Выводит посты авторов, на которых
       подписан текущий пользователь."""
    template = 'posts/follow.html'
    user = request.user
    post_list = Post.objects.filter(
        author__following__user=user
    )
    paginator = Paginator(post_list, settings.ARTICLES_SELECTION)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    """Делает подписку на автора."""
    user = request.user
    author = get_object_or_404(User, username=username)
    if author != user:
        user.follower.get_or_create(
            user=user,
            author=author
        )
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    """Отписывает пользователя от автора."""
    user = request.user
    author = get_object_or_404(User, username=username)
    follow = Follow.objects.filter(
        user=user,
        author=author
    )
    if follow.exists():
        follow.delete()
    return redirect('posts:profile', username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %}
    Редактировать пост
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}
{% block content %}
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-body">
              <div class="card-header">
                {% if is_edit %}
                  Редактировать запись
                {% else %}
                  Добавить запись
                {% endif %}
              </div>
              {% if is_edit %}
              {% if request.user == post.author %}
              <form 
              method="post"
              enctype="multipart/form-data"
              action="{% url 'posts:post_edit' post_id %}">
                {% csrf_token %}
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст поста<span class="required text-danger" >*</span>
                    </label>
                    {{ form.text }}
                    <span class="helptext text-muted">Текст нового поста</span>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">Group</label>
                    {{ form.group }}
                    <span class="helptext text-muted">
                      Группа, к которой будет относиться пост
                    </span>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_image">
                      Картинка                      
                    </label>
                    <input type="file" name="image" accept="image/*" class="form-control" id="id_image">                      
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %} 
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %}
                    </button>
                  </div>
              </form>
              {% endif %}
              {% else %}
              {% if form.errors %}
                {% for field in form %}
                  {% for error in field.errors %}            
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endif %}
              <form 
              method="post"
              enctype="multipart/form-data"
              action="{% url 'posts:post_create' %}">
              {% csrf_token %}
                <div class="form-group row my-3 p-3">
                  <label for="id_text">
                    Текст поста<span class="required text-danger" >*</span>
                  </label>
                  {{ form.text }}
                  <span class="helptext text-muted">Текст нового поста</span>
                </div>
                <div class="form-group row my-3 p-3">
                  <label for="id_group">Group</label>
                  {{ form.group }}
                  <span class="helptext text-muted">
                    Группа, к которой будет относиться пост
                  </span>
                </div>
                <div class="form-group row my-3 p-3">
                  <label for="id_image">
                    Картинка                      
                  </label>
                  <input type="file" name="image" accept="image/*" class="form-control" id="id_image">                      
                </div>
                <div class="d-flex justify-content-end">
                  <button type="submit" class="btn btn-primary">
                    <!--{% if is_edit %}
                      Сохранить
                    {% else %}
                      Добавить
                    {% endif %}-->
                    Добавить
                  </button>
                </div>
            </form>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
  Подписки пользователя {{ user.get_full_name }}
{% endblock %}

{% block content %}
{% include 'posts/includes/switcher.html' with follow=True %}
  {% for post in page_obj %}
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
        <a href="{% url 'posts:profile' post.author.username %}">
          все посты пользователя
      </a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "960x339" padding=True upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text }}</p>
    <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
    {% if post.group %}    
      <a href="{% url 'posts:group_list' post.group.slug %}">
        все записи группы
      </a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  
  {% include 'posts/includes/paginator.html' %}

{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
  Записи сообщества {{ group.title }}
{% endblock %}

{% block content %}
<h1>{{ group.title }}</h1>
<p>
  {{ group.description }}
</p>
  {% for post in page_obj %}
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
        <a href="{% url 'posts:profile' post.author.username %}">
          все посты пользователя
        </a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text }}</p>
     <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
    {% if post.group %}
      <a href="{% url 'posts:group_list' post.group.slug %}">
        все записи группы
      </a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}

  {% include 'posts/includes/paginator.html' %}

{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
  Последние обновления на сайте
{% endblock %}

{% block content %}
{% include 'posts/includes/switcher.html' with index=True %}
  {% for post in page_obj %}
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
        <a href="{% url 'posts:profile' post.author.username %}">
          все посты пользователя
      </a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "960x339" padding=True upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text }}</p>
    <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
    {% if post.group %}    
      <a href="{% url 'posts:group_list' post.group.slug %}">
        все записи группы
      </a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}

  {% include 'posts/includes/paginator.html' %}

{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
  Пост {{ post.text|truncatechars:30 }}
{% endblock %}

{% block content %}
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            <!-- если у поста есть группа -->
            {% if post.group %}   
              <li class="list-group-item">
                Группа: {{ post.group }}
                <a href="{% url 'posts:group_list' post.group.slug %}">
                  все записи группы
                </a>
            {% endif %}    
              </li>
              <li class="list-group-item">
                Автор:
                 {{ post.author.get_full_name }} {{ post.author.username }}
              </li>
              <li 
              class="list-group-item d-flex justify-content-between
              align-items-center">
              Всего постов автора:  <span >{{ post_number }}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author.username %}">
                все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>{{ post.text }}</p>
          <!-- эта кнопка видна только автору -->
          {% if request.user == post.author %}
            <a 
            class="btn btn-primary" 
            href="{% url 'posts:post_edit' post.id %}">
              редактировать запись
            </a>
          {% endif %}
        </article>
      </div> 
      {% load user_filters %}

      {% if user.is_authenticated %}
      <div class="card my-4">
        <h5 class="card-header">Добавить комментарий:</h5>
          <div class="card-body">
          <form method="post" action="{% url 'posts:add_comment' post.id %}">
            {% csrf_token %}      
            <div class="form-group mb-2">
              {{ form.text|addclass:"form-control" }}
            </div>
            <button type="submit" class="btn btn-primary">Отправить</button>
          </form>
          </div>
        </div>
      {% endif %}

      {% for comment in comments %}
        <div class="media mb-4">
          <div class="media-body">
            <h5 class="mt-0">
              <a href="{% url 'posts:profile' comment.author.username %}">
                {{ comment.author.username }}
              </a>
            </h5>
            <p>
              {{ comment.text }}
            </p>
          </div>
        </div>
      {% endfor %}
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
  Профайл пользователя {{ author.get_full_name }}
{% endblock %}

{% block content %}
{% for post in page_obj %}
  <div class="mb-5">        
    <h1>Все посты пользователя {{ post.author.get_full_name }} </h1>
    <h3>Всего постов: {{ post_number }} </h3> 
      {% if author != request.user %} 
        {% if following %}
          <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}" role="button"
          >
            Отписаться
          </a>
        {% else %}
          <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
            Подписаться
          </a>
        {% endif %}
      {% endif %} 
  </div>
        <article>
          <ul>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }} 
            </li>
          </ul>
          {% thumbnail post.image "960x339" padding=True upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>{{ post.text }}</p>
          <a href="{% url 'posts:post_detail' post.id %}">
            подробная информация 
          </a>
        </article>
        {% if post.group %}       
         <a href="{% url 'posts:group_list' post.group.slug %}">
           все записи группы
          </a>        
        {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
        <!-- Остальные посты. после последнего нет черты -->
{% endfor %}
  {% include 'posts/includes/paginator.html' %} 
{% endblock %}